appTwo/urls.py
from django.conf.urls import url
from  django.urls import path
from  . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('users', views.users, name='index')
]

django_form/urls.py
from django.conf.urls import url
from  django.urls import path
from  . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('formview', views.form_view, name='form-view')
]

django_master/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('appTwo.urls')),
    path('formapp/', include('django_form.urls')),
    path('modelform/', include('model_form.urls')),
    path('urlapp/',include('django_url.urls')),
    path('admin/', admin.site.urls),
]

django_url/urls.py
from  django.conf.urls import url
from django.urls import path
from . import views

app_name ='urlapp'


urlpatterns = [
    path('', views.index, name='index'),
    path('other', views.other, name='other'),
    path('relative', views.relative, name='relative'),

]

model_form/urls.py
from django.conf.urls import url
from  django.urls import path
from  . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('view', views.data_view, name='form-view')
]

appTwo/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=128, unique=True)

django_form/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class User_df(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=128, unique=True)

django_url/models.py
from django.db import models

# Create your models here.

model_form/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class User_md(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=128, unique=True)

django_form/forms.py
from django import forms
from django.core import validators

def check_x(value):
    if value[0].lower() != 'x':
        raise forms.ValidationError(" name start with a X")

class Formname(forms.Form):
    name = forms.CharField(validators=[check_x])
    email = forms.EmailField()
    verify_email =forms.EmailField(label= " Re enter Email ")
    text =forms.CharField(widget=forms.Textarea)
    botcap = forms.CharField(required=False,
                             widget=forms.HiddenInput,
                             validators=[validators.MaxLengthValidator(0)])
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail =all_clean_data['verify_email']

        if email != vemail:
            raise  forms.ValidationError(" make sure email match ")

model_form/forms.py
from django import forms
from django.core import validators

from .models import User_md

class Newuserform(forms.ModelForm):
    class Meta :
        model = User_md
        fields = '__all__'

appTwo/views.py
from django.shortcuts import render
from  .models import User
# Create your views here.
def index(request):
    return render(request,'apptwo/index.html')

def users(request):
    user_list = User.objects.order_by('first_name')
    user_dict = {'users':user_list}
    return render(request,'apptwo/user.html',context=user_dict)

django_form/views.py
from django.shortcuts import render


from .forms import Formname

# Create your views here.
def index(request):
    return render(request,'django_form/index.html')

def form_view(request):
    form = Formname()

    if request.method == 'POST':
        form = Formname(request.POST)

        if form.is_valid():
            print("form is valid")
            print("name :"+ form.cleaned_data['name'])
            print("email :"+form.cleaned_data['email'])
            print("text :"+form.cleaned_data['text'])

    return render(request,'django_form/form.html',{'form': form})

django_url/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'welcome to my tutorails', 'number':200}
    return render(request,'django_url/index.html', context_dict)

def other(request):
    return render(request, 'django_url/other.html')

def relative(request):
    return render(request,'django_url/relative-url.html')

model_form/views.py
from django.shortcuts import render

# Create your views here.

from .forms import  Newuserform
# Create your views here.
def index(request):
    return render(request,'model_form/index.html')

def data_view(request):
    form =Newuserform()

    if request.method == "POST":
        form = Newuserform(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(' Error in from ')
    return render(request,'model_form/form.html', {'form':form})

templates/apptwo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> welcome </h1>

</body>
</html>

templates/apptwo/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h4> user list here</h4>
{% if users %}

     <ol>
         {% for person in users %}
         <ul>
             <li> First name {{person.first_name }}</li>
             <li> last name {{ person.last_name }}</li>
             <li> email {{person.email }}</li>
         </ul>
         {% endfor%}
     </ol>
{% endif%}
</body>
</html>

templates/django_form/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forms </title>
</head>
<body>

<p> fill out form </p>
<form method="POST">
 {{ form.as_p}}
    {% csrf_token %}
    <button type="submit" value="submit"> submit</button>
</form>
</body>
</html>

templates/django_form/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
<h5> form app working </h5>
<p> open form </p>
</body>
</html>

templates/django_url/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
</head>
<body>
<a href="{% url 'urlapp:other' %}">go to other page </a>
<br/>
<a href="{% url 'admin:index' %}"> admin page</a>

{% block block_body%}

{% endblock%}

</body>
</html>

templates/django_url/index.html
<!DOCTYPE html>

{% extends "django_url/base.html" %}

 {% block block_body %}
    <h1> welcome </h1>
    <h1> this is index page </h1>
    <h2> {{ text}} {{ text|upper}}  {{ number}}</h2>
    <h3> custom filiter {{ text|cut:'welcome'}}</h3>
{% endblock %}

templates/django_url/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1> welcome to other page</h1>
</body>
</html>

templates/django_url/relative-url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Relative URL django</title>
</head>
<body>

<h1> welcome to relative URL </h1>
</body>
</html>

templates/model_form/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forms </title>
</head>
<body>

<p> fill out form </p>

<p> fill out form </p>
<form method="POST">
 {{ form.as_p}}
    {% csrf_token %}
    <input type="submit" class="" value="submit">
</form>

</body>
</html>

templates/model_form/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
<h5> modal form app working </h5>
<p> open modal  form </p>
</body>
</html>